[package]
name = "danwi"
version = "0.1.1"
edition = "2024"
description = "A units library"
authors = ["David Park <dpjungmin@gmail.com>"]
repository = "https://github.com/dpjungmin/danwi"
license = "MIT OR Apache-2.0"

[dependencies]
